export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white flex flex-col min-h-screen m-0">
        <main className="flex-1 flex flex-col items-center justify-center">
          {children}
        </main>
        <footer className="text-center py-2 border-t border-gray-700 mt-auto">
          Made by Kwak DO Young
        </footer>
      </body>
    </html>
  )
}
